---
- name: Delete {{ name }} service
  shell: "kubectl delete service {{ name }} --namespace={{ ns }}"
  ignore_errors: yes
  when: with_list is not defined

- name: "Delete {{ naming.prefix }} services"
  shell: "kubectl delete service {{ naming-prefix }}-{{ item[naming.prop] }} --namespace={{ ns }}"
  ignore_errors: yes
  with_items: "{{ with_list }}"
  when: with_list is defined and naming is defined

  #- name: Wait for {{ name }} to be deleted
  #shell: "kubectl get service --namespace={{ ns }}"
  #register: result
  #until: "result.stdout.find(name) == -1"
  #retries: "{{ retry.max }}"
  #delay: "{{ retry.delay }}"
  #when: with_list is defined and naming is defined

- name: "Create {{ name }} service (from file: {{ yamls }}/{{ file }}-service.yml)"
  shell: "kubectl create -f {{ yamls }}/{{ file }}-service.yml"
  when: with_list is not defined

- name: "Create {{ naming.prefix }} services"
  shell: "kubectl create -f {{ yamls }}/{{ naming.prefix }}-{{ item[naming.prop] }}-service.yml"
  with_items: "{{ with_list }}"
  when: with_list is defined and naming is defined
