---
- name: Delete {{ name }} service
  shell: "kubectl delete service {{ name }} --namespace={{ ns }}"
  ignore_errors: yes

- name: Wait for {{ name }} to be deleted
  shell: "kubectl get service --namespace={{ ns }}"
  register: result
  until: "result.stdout.find(name) == -1"
  retries: "{{ retry.max }}"
  delay: "{{ retry.delay }}"

- name: Create {{ name }} service (from file: {{ yamls }}/{{ file }}-service.yml)
  shell: "kubectl create -f {{ yamls }}/{{ file }}-service.yml"
