---
- name: Delete {{ svc_display_name }} service
  shell: "kubectl delete service {{ svc_name }} --namespace={{ ns }}"
  ignore_errors: yes


- name: Wait for {{ svc_display_name }} to be deleted
  shell: "kubectl get service --namespace={{ ns }}"
  register: result
  until: "result.stdout.find(svc_name) == -1"
  retries: "{{ retry.max }}"
  delay: "{{ retry.delay }}"

- name: Create {{ svc_display_name }} service
  shell: "kubectl create -f {{ yamls }}/{{ svc_name }}-service.yml"
